DROP TABLE USERS CASCADE;
DROP TABLE PASSWORD_CHANGE_REQUESTS CASCADE;
DROP TABLE USER_SESSION_TOKENS CASCADE;
DROP TABLE GROUPS CASCADE;
DROP TABLE GROUP_REQUESTS CASCADE;
DROP TABLE USER_SCHEDULES CASCADE;
DROP TABLE DRIVER_CARPOOL_SCHEDULES CASCADE;