DROP TABLE IF EXISTS USERS CASCADE;
DROP TABLE IF EXISTS PASSWORD_CHANGE_REQUESTS CASCADE;
DROP TABLE IF EXISTS USER_SESSION_TOKENS CASCADE;
DROP TABLE IF EXISTS GROUPS CASCADE;
DROP TABLE IF EXISTS GROUP_REQUESTS CASCADE;
DROP TABLE IF EXISTS USER_SCHEDULES CASCADE;
DROP TABLE IF EXISTS DRIVER_CARPOOL_SCHEDULES CASCADE;